#!/bin/tcsh
#PBS -N HASPECT_TOYFITS
#PBS -m abe 
#PBS -l walltime=100:00:00
#PBS -V
#Make a directory to work in
mkdir -p /home/dglazier/$JOBNAME
cd /home/dglazier/$JOBNAME
#mkdir -p /scratch/dglazier/$OUTDIR/$JOBNAME
#cd /scratch/dglazier/$OUTDIR/$JOBNAME

echo ' analysing bin ' $JOBNAME
echo $HOST

#set env variables
echo $RUNMAC

cp $LAUNCH/RooHSSphHarMoments.cxx .
cp $LAUNCH/RooHSSphHarMoments.h .
cp $LAUNCH/phasespace_res.root .
cp $CREATEMODEL .
cp $RUNMAC hsrun.C
cp $FILEDIR/$JOBNAME.root ToyData.root
#setenv INPUT "Farm"$JOBNAME".root"
setenv LOG "Farm"$JOBNAME".log"

#root -l  --farm --hsfit --RooHSSphHarMoments.cxx hsrun.C
root -l -b -q --farm --hsfit --RooHSSphHarMoments.cxx hsrun.C  >& $LOG

mkdir -p $FILEDIR/$OUTDIR/$JOBNAME
#copy output files to destination
scp Results* dglazier@npc72:$FILEDIR/$OUTDIR/$JOBNAME/.
scp $LOG dglazier@npc72:$FILEDIR/$OUTDIR/$JOBNAME/.

ls -lh 

#tidy up
cd ../../
rm -r $OUTDIR/$JOBNAME

echo 'all done and tidied up'


