#!/bin/tcsh
#PBS -N HASPECT_SW
#PBS -m abe 
#PBS -M Derek.Glazier@glasgow.ac.uk
#PBS -l walltime=100:00:00
#PBS -V
#Make a directory to work in
mkdir -p /home/dglazier/$JOBNAME
cd /home/dglazier/$JOBNAME
#mkdir -p /scratch/dglazier/$JOBNAME
#cd /scratch/dglazier/$JOBNAME

echo ' analysing bin ' $JOBNAME
echo $HOST

#set env variables
setenv INPUT "Farm"$JOBNAME".root"
setenv LOG "Farm"$JOBNAME".log"


#root -l -b -q --farm --hsfit --SKNewPDF.cxx '$RUNMAC'  >& $LOG
root -l -b  --farm --hsfit --SKNewPDF.cxx '$RUNMAC' 
#copy output files to destination
cp Results* $FILEDIR/.
cp Weights* $FILEDIR/.
cp $LOG $FILEDIR/.

ls -lh 

#tidy up
cd ../
#rm -r $JOBNAME

echo 'all done and tidied up'


