/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef SKNEWPDF
#define SKNEWPDF

#include "RooAbsPdf.h"
#include "RooHSEventsPDF.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class SKNewPDF : public RooHSEventsPDF {
public:
  SKNewPDF() {} ; 
  SKNewPDF(const char *name, const char *title,
	      RooAbsReal& _Phi,
	      RooAbsReal& _Pol,
	      RooAbsCategory& _PolState,
	      RooAbsReal& _A,
	      RooAbsReal& _B);
  SKNewPDF(const SKNewPDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new SKNewPDF(*this,newname); }
  inline virtual ~SKNewPDF() { }

protected:
  Double_t fMCPhi;
  Double_t fMCPol;
  Int_t fMCPolState;

  RooRealProxy Phi ;
  RooRealProxy Pol ;
  RooCategoryProxy PolState ;
  RooRealProxy A ;
  RooRealProxy B ;
  
  Double_t evaluate() const ;
  Double_t evaluateMC() const ;
  void MakeSets();

private:

  ClassDef(SKNewPDF,1) // Your description goes here...
};
 
#endif
