/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef TESTPDF
#define TESTPDF

#include "RooAbsPdf.h"
#include "RooHSAbsEventsPDF.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class TESTPDF : public RooAbsPdf {
public:
  virtual Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars,const char* rangeName) const;
  TESTPDF() {} ; 
  TESTPDF(const char *name, const char *title,
	      RooAbsReal& _X,
	      RooAbsReal& _Y,
	      RooAbsReal& _A,
	      RooAbsReal& _B);
  TESTPDF(const TESTPDF& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new TESTPDF(*this,newname); }
  inline virtual ~TESTPDF() { }

protected:
  Double_t fMCX;
  Double_t fMCY;

  RooRealProxy X ;
  RooRealProxy Y ;
  RooRealProxy A ;
  RooRealProxy B ;
  
  Double_t evaluate() const ;
  Double_t evaluateMC() const ;

private:

  ClassDef(TESTPDF,1) // Your description goes here...
};
 
#endif
