#!/bin/tcsh
#PBS -N HASPECT_TOYFITS
#PBS -l walltime=100:00:00
#PBS -V
#Make a directory to work in
mkdir -p /home/dglazier/$HS_OUTDIR/$HS_JOBNAME
cd /home/dglazier/$HS_OUTDIR/$HS_JOBNAME
#mkdir -p /scratch/dglazier/$OUTDIR/$HS_JOBNAME
#cd /scratch/dglazier/$OUTDIR/$HS_JOBNAME

echo ' analysing bin ' $HS_JOBNAME
echo $HOST

#set env variables
echo $HS_RUNMAC

#copy macros
cp $HS_FITMODEL .
cp $HS_RUNMAC hsrun.C
setenv LOG "Farm"$HS_JOBNAME".log"

#execute root
#you may want to add extra classes as part of command line args
#root -l  --farm --hsfit hsrun.C
root -l -b -q --farm --hsfit hsrun.C  >& $LOG

mkdir -p $HS_FILEDIR/$HS_OUTDIR/$HS_JOBNAME
#copy output files to destination
#scp Results* dglazier@npc72:$FILEDIR/$OUTDIR/$JOBNAME/.
#scp $LOG dglazier@npc72:$FILEDIR/$OUTDIR/$JOBNAME/.
cp $LOG $HS_FILEDIR/$HS_OUTDIR/$HS_JOBNAME/.
cp Res*.root $HS_FILEDIR/$HS_OUTDIR/$HS_JOBNAME/.

ls -lh 

#tidy up
cd ../../
rm -r $HS_OUTDIR/$HS_JOBNAME

echo 'all done and tidied up'


